# Generated by Django 2.0.2 on 2018-03-06 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.Game')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.Question')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='games', through='trivia.QuestionState', to='trivia.Question'),
        ),
    ]
