# Generated by Django 2.0.2 on 2018-03-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_auto_20180306_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='key',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
