# Generated by Django 2.0.2 on 2018-03-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0005_auto_20180310_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'ordering': ('order', 'title')},
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
