# Generated by Django 2.0.2 on 2018-03-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0006_auto_20180312_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
