# Generated by Django 2.0.2 on 2018-03-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0007_auto_20180313_1210'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('game', 'name')},
        ),
    ]
