# Generated by Django 3.2.4 on 2021-06-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0013_auto_20210527_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField(default=1)),
                ('is_final', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('game', 'round'),
            },
        ),
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'ordering': ('title',), 'verbose_name_plural': 'question categories'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='game',
            name='final_round',
        ),
        migrations.RemoveField(
            model_name='game',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='questioncategory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='questioncategory',
            name='round',
        ),
        migrations.DeleteModel(
            name='QuestionState',
        ),
        migrations.AddField(
            model_name='gameround',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='trivia.game'),
        ),
        migrations.AlterUniqueTogether(
            name='gameround',
            unique_together={('game', 'round')},
        ),
    ]
