# Generated by Django 3.2.4 on 2021-06-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0015_auto_20210611_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorystate',
            options={'ordering': ('game_round', 'order', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='categorystate',
            unique_together={('game_round', 'category')},
        ),
    ]
