# Generated by Django 3.2.4 on 2021-06-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0017_alter_question_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionCategory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name_plural': 'categories'},
        ),
    ]
