# Generated by Django 3.2.4 on 2021-06-13 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0019_questionstate_requires_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionstate',
            old_name='requires_bid',
            new_name='requires_wager',
        ),
    ]
